//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Francesco Bonizzi")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0+e3c1a5eb7d946942c0a29a9e829946ea7c04d9c7")]
[assembly: System.Reflection.AssemblyProductAttribute("RestartOnCrash")]
[assembly: System.Reflection.AssemblyTitleAttribute("RestartOnCrash")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]

// Generato dalla classe WriteCodeFragment di MSBuild.

